// 操作日志的「一句话」：契约文档里每一种 kind 的真实例子（后端测试生成、contractExamples.json
// 里是原样拷贝），在 zh / en 下都要拼出一句人话——不漏 kind、不漏文案键、不出英文枚举 / JSON /
// 订单号；止损止盈的设置 / 移动 / 移除 / 不变 / 原值未知，全平 / 部分平 / 仓位已不在各自说对。
// contractExamples.json 由契约文档的 ```json 例子抽出（106 条，53 种 kind 各 2 条）；后端改了
// params 重新生成契约后，照同样的办法重抽一次。
// The activity sentence: every kind's real examples from the contract doc (generated by the
// backend tests, copied verbatim into contractExamples.json) must read as plain language
// in zh and en — no missing kind or copy key, no English enums / JSON / order numbers —
// and the SL/TP set / move / remove / same / unknown and full / partial / gone cases must
// each say the right thing. contractExamples.json is extracted from the contract's ```json
// examples (106 items, two per kind); re-extract it when the backend regenerates the contract.
import { describe, expect, it } from 'vitest'
import type { ActivityItem } from '../../../api/types'
import examples from './contractExamples.json'
import { ACTIVITY_KINDS, actorLabel, chipsFor, failReason, fmtLots, fmtPnl, kindName, pxDigits, renderEvent, symDigits } from './renderEvent'
import { makeT } from './testT'

const EXAMPLES = examples as unknown as ActivityItem[]
const zh = makeT('zh')
const en = makeT('en')
const LANGS = [['zh', zh], ['en', en]] as const

// 契约 §6 的机器可读清单（53 种）/ the contract's §6 machine-readable list (53 kinds)
const CONTRACT_KINDS = [
  'admin.agent_assign', 'admin.announcement', 'admin.bulk_edit', 'admin.competition', 'admin.competition_participant',
  'admin.email', 'admin.gamification', 'admin.invite_link', 'admin.ops', 'admin.other', 'admin.setting', 'admin.ticket',
  'admin.user_attribution', 'admin.user_disable', 'admin.user_edit', 'admin.user_enable', 'admin.user_plan',
  'admin.user_role', 'admin.verify_email', 'agent.plan', 'auto.partial_tp', 'auto.settings', 'auto.sl', 'deal.close',
  'deal.stopout_group', 'mt5.bind', 'mt5.reverify', 'mt5.revoked', 'mt5.unbind', 'pending.cancel', 'pending.modify',
  'pending.place', 'plan.auto_expire', 'plan.invite_trial', 'plan.payment', 'plan.payment_issue', 'plan.refund',
  'plan.trial_claim', 'sltp.modify', 'trade.close', 'trade.close_all', 'trade.corrected', 'trade.open', 'trade.other',
  'user.api_token_reset', 'user.email_verified', 'user.login', 'user.nickname', 'user.password_changed',
  'user.password_reset', 'user.password_reset_requested', 'user.phone_set', 'user.register',
]

// 句子里允许出现的大写词：品种、会员等级名、例子里用户自己起的名字（FB 投放、KOL 备注）。
// Upper-case words allowed in a sentence: symbols, plan names, and user-chosen labels in the examples.
const ALLOWED_CAPS = new Set(['XAUUSD', 'USDJPY', 'GBPUSD', 'EURUSD', 'PRO', 'FREE', 'API', 'FB', 'KOL', 'USD', 'UTC'])

function item(kind: string, params: Record<string, unknown>, extra: Partial<ActivityItem> = {}): ActivityItem {
  return {
    key: `o:${kind}`,
    ts: '2026-10-09T06:03:21.123456Z',
    at: null,
    cat: 'trade',
    kind,
    params,
    status: 'ok',
    tags: [],
    abnormal: false,
    actor: { type: 'self', id: null, name: null, email: null },
    user: { id: 'u1', nickname: '美琳', email: 'meilin@example.com' },
    users_count: null,
    login: '62345678',
    account: { channel: 'bridge', demo: false, removed: false, revoked: false },
    children: null,
    ...extra,
  }
}

const allWithChildren = (list: ActivityItem[]) => list.flatMap((i) => [i, ...(i.children ?? [])])

describe('kind 清单 / kind list', () => {
  it('前端认得契约里的全部 53 种，且一种不多 / the frontend knows exactly the contract’s 53 kinds', () => {
    expect([...ACTIVITY_KINDS].sort()).toEqual([...CONTRACT_KINDS].sort())
    expect(ACTIVITY_KINDS.length).toBe(53)
  })

  it('例子覆盖每一种 kind / the examples cover every kind', () => {
    const seen = new Set(EXAMPLES.map((e) => e.kind))
    expect([...seen].sort()).toEqual([...CONTRACT_KINDS].sort())
  })

  it('每种 kind 都有通用说法 / every kind has a generic name', () => {
    for (const [, t] of LANGS) {
      for (const k of ACTIVITY_KINDS) {
        const name = kindName(k, t)
        expect(name, k).not.toContain('admin.log')
        expect(name.length, k).toBeGreaterThan(1)
      }
    }
  })
})

describe.each(LANGS)('%s：每个契约例子都拼成一句人话 / every contract example reads as a sentence', (lang, t) => {
  for (const ex of allWithChildren(EXAMPLES)) {
    it(`${ex.kind} ${ex.key}`, () => {
      const r = renderEvent(ex, t)
      const text = r.text
      expect(text.trim().length).toBeGreaterThan(3)
      // 没有漏翻的文案键、没插上的占位、没有 JS 值漏进来 / no raw keys, placeholders or JS values
      expect(text).not.toMatch(/admin\.log\.|\{\{|undefined|NaN|\[object|\bnull\b|\btrue\b|\bfalse\b/)
      // 没有 JSON / no JSON
      expect(text).not.toMatch(/[{}[\]]/)
      // 不出英文枚举（BUY / SELL_LIMIT / FAILED / MOBILE / SO …）/ no English enums
      const caps = (text.match(/\b[A-Z]{2,}(?:_[A-Z]+)*\b/g) ?? []).filter((w) => !ALLOWED_CAPS.has(w))
      expect(caps).toEqual([])
      // 不出 snake_case 原值（password_changed / user_cancelled / trail_trigger_r …）；
      // admin.other 是「原样显示、绝不丢」的兜底，字段名本来就该原样出现
      // No raw snake_case values; admin.other is the never-drop fallback and shows its field verbatim
      if (ex.kind === 'admin.other') {
        expect(text).toContain(String(ex.params.field))
      } else {
        expect(text).not.toMatch(/\b[a-z]+_[a-z_]+\b/)
      }
      // 不出订单号 / 仓位号、券商原话 / no order numbers or broker messages
      if (typeof ex.params.ticket === 'number') expect(text).not.toContain(String(ex.params.ticket))
      if (typeof ex.params.msg === 'string') expect(text).not.toContain(ex.params.msg)
      // 句子里的盈亏段就是 params.pnl / the P/L part is params.pnl
      const pnlParts = r.parts.filter((p) => typeof p !== 'string')
      if (typeof ex.params.pnl === 'number') expect(pnlParts).toEqual([{ pnl: ex.params.pnl }])
      // 语言真的换了 / the language really is the requested one
      if (lang === 'zh') expect(text).toMatch(/[一-鿿]/)
      else expect(text).toMatch(/^[\x20-\x7e“”’…·—→一-鿿　-〿＀-￯]+$/)
    })
  }
})

describe('交易句子 / trading sentences', () => {
  const sltp = (over: Record<string, unknown>) =>
    item('sltp.modify', { sym: 'XAUUSD', side: 'BUY', pos_vol: 0.1, sl: null, tp: null, prev_sl: null, prev_tp: null, sl_op: 'same', tp_op: 'same', ...over })

  it('设计里的样句一字不差 / the design’s sample sentence, verbatim', () => {
    const it1 = sltp({ sl: 2648.5, prev_sl: 2640, tp: 2700, prev_tp: 2700, sl_op: 'move', tp_op: 'same' })
    expect(renderEvent(it1, zh).text).toBe('移动止损 2640.00 → 2648.50，止盈不变 —— XAUUSD 买单 0.10 手')
    expect(renderEvent(it1, en).text).toBe('Move stop loss 2640.00 → 2648.50, take profit unchanged — XAUUSD buy 0.10 lots')
  })

  it('设置 / 移除 / 原值未知 / 取消 / 都没变 / set, remove, unknown previous, cleared, unchanged', () => {
    expect(renderEvent(sltp({ sl: 1.09, sl_op: 'set', tp: null, prev_tp: 1.07, tp_op: 'remove' }), zh).text).toBe(
      '设置止损 1.09，移除止盈（原 1.07） —— XAUUSD 买单 0.10 手',
    )
    expect(renderEvent(sltp({ sl: 1.09, sl_op: 'set', tp: null, prev_tp: 1.07, tp_op: 'remove' }), en).text).toBe(
      'Set stop loss 1.09, remove take profit (was 1.07) — XAUUSD buy 0.10 lots',
    )
    // 上线前的旧改单：原值不知道，只能说「改为」/ legacy rows: previous unknown, only "changed to"
    expect(renderEvent(sltp({ sl: 2390, sl_op: 'changed', tp: 2425, tp_op: 'changed' }), zh).text).toBe(
      '止损改为 2390.00，止盈改为 2425.00 —— XAUUSD 买单 0.10 手',
    )
    expect(renderEvent(sltp({ sl: null, sl_op: 'changed', tp_op: 'same' }), zh).text).toBe('取消止损，止盈不变 —— XAUUSD 买单 0.10 手')
    expect(renderEvent(sltp({}), zh).text).toBe('提交改单，止损止盈都没变 —— XAUUSD 买单 0.10 手')
    // 只动了止盈：变了的那一侧排前面 / only TP moved: the changed side comes first
    expect(renderEvent(sltp({ tp: 2430, prev_tp: 2425, tp_op: 'move', sl_op: 'same' }), zh).text).toBe(
      '移动止盈 2425.00 → 2430.00，止损不变 —— XAUUSD 买单 0.10 手',
    )
  })

  it('全平 / 部分平 / 仓位已不在 / full, partial and gone closes', () => {
    const base = { sym: 'XAUUSD', side: 'BUY', px: 2405.5, pnl: -12.3, pnl_pending: false, gone: false }
    const full = item('trade.close', { ...base, vol: 0.3, pos_vol: 0.3, remain: null, partial: false })
    expect(renderEvent(full, zh).text).toBe('平仓 —— XAUUSD 买单 0.30 手，成交价 2405.50，盈亏 -12.30')
    const part = item('trade.close', { ...base, vol: 0.1, pos_vol: 0.3, remain: 0.2, partial: true }, { tags: ['partial'] })
    expect(renderEvent(part, zh).text).toBe('部分平仓 0.10 手（共 0.30 手，剩 0.20 手） —— XAUUSD 买单，成交价 2405.50，盈亏 -12.30')
    expect(renderEvent(part, en).text).toBe('Partial close 0.10 lots (of 0.30, 0.20 left) — XAUUSD buy, filled at 2405.50, P/L -12.30')
    // 仓位已经不在：不说「部分」、不报成交价和盈亏 / gone: never claims a partial close, no price or P/L
    const gone = item('trade.close', { ...base, vol: 0.1, pos_vol: 0.3, remain: 0.2, partial: true, gone: true, px: null, pnl: null }, { tags: ['gone'] })
    const goneZh = renderEvent(gone, zh).text
    expect(goneZh).toContain('仓位已经不在了')
    expect(goneZh).not.toContain('部分')
    expect(renderEvent(gone, en).text).not.toMatch(/partial/i)
    // 仓位手数不知道（旧行）：只说平了多少 / unknown position size (legacy): just the closed volume
    const legacy = item('trade.close', { ...base, vol: 0.1, pos_vol: null, remain: null, partial: true })
    expect(renderEvent(legacy, zh).text).toBe('部分平仓 0.10 手 —— XAUUSD 买单，成交价 2405.50，盈亏 -12.30')
    // 盈亏还没回来 / P/L not synced yet
    const pending = item('trade.close', { ...base, vol: 0.3, pos_vol: 0.3, partial: false, pnl: null, pnl_pending: true })
    expect(renderEvent(pending, zh).text).toBe('平仓 —— XAUUSD 买单 0.30 手，成交价 2405.50，盈亏同步中')
    expect(renderEvent(pending, en).text).toBe('Close — XAUUSD buy 0.30 lots, filled at 2405.50, P/L still syncing')
  })

  it('自动分批止盈与自动移动止损 / auto partial TP and auto stop moves', () => {
    const ptp = item('auto.partial_tp', { sym: 'XAUUSD', side: 'BUY', vol: 0.05, pos_vol: 0.1, remain: 0.05, partial: true, px: 2412, pnl: 53.25, pnl_pending: false, gone: false })
    expect(renderEvent(ptp, zh).text).toBe('自动分批止盈：平掉 0.05 手（共 0.10 手，剩 0.05 手） —— XAUUSD 买单，成交价 2412.00，盈亏 +53.25')
    const be = item('auto.sl', { mode: 'be', sym: 'XAUUSD', side: 'SELL', sl: 2401.35, prev_sl: 2410, moves: 1 })
    expect(renderEvent(be, zh).text).toBe('自动保本：止损移到开仓价 2401.35（原 2410.00） —— XAUUSD 卖单')
    const restore = item('auto.sl', { mode: 'restore', sym: 'XAUUSD', side: 'BUY', sl: 2390, prev_sl: null, moves: 1 })
    expect(renderEvent(restore, zh).text).toBe('止损被清掉后，自动补回止损 2390.00 —— XAUUSD 买单')
    const legacy = item('auto.sl', { mode: null, sym: 'XAUUSD', side: 'BUY', sl: 2390, prev_sl: null, moves: 1 })
    expect(renderEvent(legacy, en).text).toBe('Auto-manage set the stop loss to 2390.00 — XAUUSD buy')
  })

  it('订单状态的结构化说明进句子，失败 / 未知靠小标签 / notes go in the sentence, fail / unknown are chips', () => {
    const open = (status: ActivityItem['status'], note: string | null) =>
      item('trade.open', { sym: 'EURUSD', side: 'SELL', vol: 1, px: null, sl: 1.1, tp: null, src: 'SIG', msg: 'TRADE_RETCODE_TIMEOUT 10012', note }, { status })
    // 超时的固定说法已经在句子里，不再跟「原因」/ the timeout wording is already there, so no reason follows
    expect(renderEvent(open('cancelled', 'timeout'), zh).text).toBe('开仓（跟信号）（超时未执行，已自动取消） —— EURUSD 卖单 1.00 手，止损 1.10000')
    expect(renderEvent(open('unknown', 'timeout_unknown'), en).text).toBe(
      'Open (from a signal) (timed out — outcome unknown, check positions) — EURUSD sell 1.00 lots, stop loss 1.10000',
    )
    const failed = open('fail', null)
    expect(renderEvent(failed, zh).text).not.toContain('10012')
    expect(renderEvent(failed, zh).text).toBe('开仓（跟信号） —— EURUSD 卖单 1.00 手，止损 1.10000，原因：券商超时未答复')
    expect(chipsFor(failed, zh).map((c) => c.label)).toEqual(['失败'])
    expect(chipsFor(open('unknown', null), en).map((c) => c.label)).toEqual(['Outcome unknown'])
    // 止损止盈没设上：句子里说，小标签也亮 / SL/TP not set: said in the sentence and chipped
    const bare = item('trade.open', { sym: 'XAUUSD', side: 'BUY', vol: 0.1, px: 2400, sl: 2390, tp: null, src: 'CHART', note: 'sltp_failed' }, { tags: ['unprotected'] })
    expect(renderEvent(bare, zh).text).toBe('开仓 —— XAUUSD 买单 0.10 手，成交价 2400.00，止损 2390.00，但止损止盈没设上')
    expect(chipsFor(bare, zh).map((c) => c.label)).toEqual(['无止损'])
  })

  it('MT5 那边的平仓：不复用 DEALER / EXPERT 的译名，共享账号列出所有人 / MT5-side closes', () => {
    const deal = (reason: string, extra: Record<string, unknown> = {}) =>
      item('deal.close', { reason, sym: 'XAUUSD', side: 'BUY', vol: 0.1, px: 2385, pnl: -48.5, leg_k: 1, leg_n: 1, holders: null, ...extra })
    expect(renderEvent(deal('SL'), zh).text).toBe('止损触发平仓 —— XAUUSD 买单 0.10 手，成交价 2385.00，盈亏 -48.50')
    expect(renderEvent(deal('OTHER'), zh).text.startsWith('在 MT5 那边平仓')).toBe(true)
    expect(renderEvent(deal('DEALER'), zh).text.startsWith('在 MT5 那边平仓')).toBe(true)
    expect(renderEvent(deal('TP', { leg_k: 2, leg_n: 3 }), zh).text).toContain('（这笔仓位第 2 次平仓，共 3 次）')
    const shared = deal('MOBILE', {
      holders: [
        { id: 'a', nickname: '美琳', email: 'm@x.com' },
        { id: 'b', nickname: null, email: 'lucas@x.com' },
      ],
    })
    expect(renderEvent(shared, zh).text).toContain('这个账号同时绑定给：美琳、lucas@x.com')
  })

  it('修改挂单只说动了的那几项：没传的不说成「不设止损」/ pending modify names only what changed, never "no stop loss" for an untouched side', () => {
    const pm = (over: Record<string, unknown>) =>
      item('pending.modify', { ticket: 880105, sym: 'XAUUSD', price: null, sl: null, tp: null, sl_op: 'keep', tp_op: 'keep', msg: null, note: null, ...over })
    // 只拖了触发价 / only the trigger was dragged
    expect(renderEvent(pm({ price: 2455 }), zh).text).toBe('修改挂单 —— XAUUSD，触发价改为 2455.00')
    expect(renderEvent(pm({ price: 2455 }), en).text).not.toMatch(/stop loss|take profit/i)
    // 设新值 / 清除 / set and remove
    expect(renderEvent(pm({ sl: 2465, sl_op: 'set', tp_op: 'remove' }), zh).text).toBe('修改挂单 —— XAUUSD，止损改为 2465.00，移除止盈')
    expect(renderEvent(pm({ sl: 2465, sl_op: 'set', tp_op: 'remove' }), en).text).toBe(
      'Modify pending order — XAUUSD, stop loss changed to 2465.00, remove take profit',
    )
    // 三项都没动 / nothing named
    expect(renderEvent(pm({}), zh).text).toBe('修改挂单 —— XAUUSD')
    for (const t of [zh, en]) {
      for (const over of [{ price: 2455 }, {}, { tp: 2410, tp_op: 'set' }]) {
        expect(renderEvent(pm(over), t).text).not.toMatch(/不设|no stop|no take/i)
      }
    }
  })

  it('结果更正：桥接超时作废的说「超时已自动取消」，不是「结果未知」/ corrections: a bridge timeout void reads as auto-cancelled, not unknown', () => {
    const corr = (was: string, note: string | null) =>
      item('trade.corrected', { was, action: 'ORDER', sym: 'USDJPY', side: 'BUY', vol: 0.2, px: 149.32, at: '2026-10-09T06:01:00.000000Z', note }, {
        key: 'e:c1', actor: { type: 'system', id: null, name: null, email: null }, abnormal: true,
      })
    const timeoutZh = renderEvent(corr('FAILED', 'timeout'), zh).text
    expect(timeoutZh).toContain('原记为「超时已自动取消」')
    expect(timeoutZh).not.toContain('结果未知')
    expect(renderEvent(corr('FAILED', 'timeout'), en).text).toContain('recorded as “auto-cancelled after a timeout”')
    expect(renderEvent(corr('FAILED', 'timeout_unknown'), zh).text).toContain('原记为「结果未知」')
    expect(renderEvent(corr('FAILED', null), zh).text).toContain('原记为「结果未知」')
    expect(renderEvent(corr('CANCELLED', null), zh).text).toContain('原记为「已撤回」')
  })
})

describe('失败原因 / failure reasons', () => {
  const open = (msg: string | null, status: ActivityItem['status'] = 'fail', over: Record<string, unknown> = {}) =>
    item('trade.open', { sym: 'XAUUSD', side: 'BUY', vol: 5, px: null, sl: null, tp: null, src: 'CHART', msg, note: null, ...over }, { status })
  const reasonOf = (msg: string, t: typeof zh, status: ActivityItem['status'] = 'fail') => failReason(open(msg, status), t)

  // 生产库近 30 天里真实出现过的原话（后面的数是条数）→ 中文 / 英文的原因
  // Real production messages from the last 30 days (counts in the comments) → zh / en reasons
  const PROD: [string, string, string][] = [
    // 609
    ['MT_RET_REQUEST_NO_MONEY: 交易被拒绝(检查品种名、手数、保证金、市场是否开市)', '保证金不足', 'not enough margin'],
    // 58
    ['MT_RET_REQUEST_CLOSE_ORDER_EXIST: 交易被拒绝(检查品种名、手数、保证金、市场是否开市)', '这笔仓位已有平仓单在处理中', 'a close order for this position is already in progress'],
    // 25
    ['MT_RET_ERR_NOTFOUND: 取价失败,无法下单(品种名是否正确?该品种是否有行情?)', '取不到行情价（品种名不对或没有行情）', 'no price for the symbol (wrong name or no quotes)'],
    // 13 + 4（网关写「#票号」，旧网关不带 #）/ the gateway writes "#ticket"; older builds omit the #
    ['MT_RET_ERR_NOTFOUND: 找不到仓位 #123456789', '找不到这笔仓位（可能已平仓）', 'position not found (probably already closed)'],
    ['MT_RET_ERR_NOTFOUND: 找不到仓位 123456789', '找不到这笔仓位（可能已平仓）', 'position not found (probably already closed)'],
    // 12
    ['账号不存在或无法读取', '账户不存在或读不到', 'account not found or unreadable'],
    // 12
    ['MT_RET_ERR_NOTFOUND: 找不到挂单 #880105(可能已成交、已过期或已撤销)', '找不到这张挂单（可能已成交、过期或已撤销）', 'pending order not found (it may have filled, expired or been cancelled)'],
    // 11 + 3（开仓 / 平仓两种说法）/ the open and close wordings
    [
      'MT_RET_REQUEST_PLACED_UNCONFIRMED: 开仓请求已被服务器接受,但未在确认时限内成交,服务器上查不到对应仓位。这张订单可能仍挂在券商的交易队列里。请不要重复提交,稍后核对持仓,必要时联系券商。',
      '券商已接受但未确认成交，请核对持仓',
      'accepted by the broker but the fill was not confirmed, check positions',
    ],
    [
      'MT_RET_REQUEST_PLACED_UNCONFIRMED: 平仓请求已被服务器接受,但未在确认时限内成交,仓位手数没有变化。',
      '券商已接受但未确认成交，请核对持仓',
      'accepted by the broker but the fill was not confirmed, check positions',
    ],
    // 7
    [': 未知接口:/trade/pending', '网关暂不支持挂单', 'the gateway does not support pending orders yet'],
    // 6
    ['保证金不足 / Insufficient funds', '保证金不足', 'not enough margin'],
    // 6 + 1
    [
      'GATEWAY_TIMEOUT: 网关两次未在时限内回话，这笔指令可能已经执行，请先核对持仓再重下 / gateway timed out twice; the order may have executed, check positions before retrying',
      '网关超时，可能已执行，请核对持仓',
      'gateway timed out, it may have executed, check positions',
    ],
    // 4
    ['MT_RET_REQUEST_INVALID_FILL: 该品种不接受本次请求的成交模式(filling mode),日志里的 FillFlags 是它声明支持的模式', '券商不支持这种成交方式', 'the broker does not accept this fill type'],
    // 2
    ['MT_RET_REQUEST_POSITION_CLOSED: 交易被拒绝(检查品种名、手数、保证金、市场是否开市)', '仓位已经平掉', 'the position is already closed'],
    // 2
    ['MT_RET_REQUEST_INVALID_STOPS: 交易被拒绝(检查品种名、手数、保证金、市场是否开市)', '止损 / 止盈价位无效（离现价太近或方向不对）', 'invalid stop loss / take profit (too close to the price or on the wrong side)'],
    // 1
    ['Gateway 响应超时', '网关响应超时', 'the gateway did not answer in time'],
    // 1
    ['下单被拒绝 / Order rejected (#10027)', '券商拒绝（终端禁用了自动交易）', 'rejected by the broker (automated trading disabled in the terminal)'],
  ]

  it('开仓失败的样句 / the failed-open sample sentence', () => {
    const it1 = open(PROD[0][0])
    expect(renderEvent(it1, zh).text).toBe('开仓 —— XAUUSD 买单 5.00 手，原因：保证金不足')
    expect(renderEvent(it1, en).text).toBe('Open — XAUUSD buy 5.00 lots, reason: not enough margin')
    expect(chipsFor(it1, zh).map((c) => c.label)).toEqual(['失败'])
  })

  for (const [msg, zhWhy, enWhy] of PROD) {
    it(`生产原话 / production message: ${msg.slice(0, 48)}`, () => {
      for (const status of ['fail', 'unknown'] as const) {
        expect(reasonOf(msg, zh, status)).toBe(zhWhy)
        expect(reasonOf(msg, en, status)).toBe(enWhy)
        const zhText = renderEvent(open(msg, status), zh).text
        expect(zhText.endsWith(`，原因：${zhWhy}`)).toBe(true)
        expect(renderEvent(open(msg, status), en).text.endsWith(`, reason: ${enWhy}`)).toBe(true)
        // 原话、返回码、编号、英文都不进中文句子 / no raw message, code, number or English in the zh sentence
        expect(zhText).not.toContain(msg)
        expect(zhText.replace('XAUUSD', '')).not.toMatch(/[A-Za-z#]|\d{4,}/)
      }
    })
  }

  it('其它常见返回码 / other common return codes', () => {
    const CODES: [string, string, string][] = [
      ['MT_RET_REQUEST_INVALID_VOLUME', '手数不对', 'invalid lot size'],
      ['MT_RET_REQUEST_INVALID_PRICE: 价格不被接受(挂单触发价可能离现价太近,小于该品种的最小距离)', '价格无效', 'invalid price'],
      ['MT_RET_REQUEST_MARKET_CLOSED', '休市', 'market closed'],
      ['MT_RET_REQUEST_TRADE_DISABLED', '禁止交易（账户或品种受限）', 'trading disabled (account or symbol restricted)'],
      ['MT_RET_REQUEST_PRICE_CHANGED', '价格变动', 'the price moved'],
      ['MT_RET_REQUEST_REQUOTE', '价格变动', 'the price moved'],
      ['MT_RET_REQUEST_LIMIT_ORDERS', '挂单数已达上限', 'pending order limit reached'],
      ['MT_RET_REQUEST_LIMIT_POSITIONS', '持仓数已达上限', 'open position limit reached'],
      ['MT_RET_REQUEST_REJECT', '券商拒绝', 'rejected by the broker'],
      ['MT_RET_REQUEST_TIMEOUT: 服务器未在超时内答复,确认 dealer 通道与请求路由配置', '券商超时未答复', 'the broker did not answer in time'],
      ['MT_RET_REQUEST_FROZEN', '订单已冻结（离现价太近）', 'the order is frozen (too close to the price)'],
      ['MT_RET_REQUEST_LOCKED', '请求被锁定，券商还在处理', 'request locked, the broker is still processing it'],
      ['MT_RET_REQUEST_ONLY_REAL', '仅限实盘账户', 'live accounts only'],
      ['MT_RET_ERR_PERMISSIONS: 权限不足,确认 manager 账号有 RIGHT_TRADES_DEALER', '网关权限不足', 'the gateway lacks permission'],
      ['TRADE_RETCODE_NO_MONEY', '保证金不足', 'not enough margin'],
      ['TRADE_RETCODE_TOO_MANY_REQUESTS', '请求太频繁', 'too many requests'],
      // 桥接的数字返回码与固定说法 / the bridge's numeric retcodes and fixed wordings
      ['下单被拒绝 / Order rejected (#10018)', '休市', 'market closed'],
      ['下单被拒绝 / Order rejected (#10040)', '持仓数已达上限', 'open position limit reached'],
      ['下单被拒绝 / Order rejected', '券商拒绝', 'rejected by the broker'],
      ['价格已变动，请重试 / Price changed, retry', '价格变动', 'the price moved'],
      ['市场已休市 / Market closed', '休市', 'market closed'],
      ['止损止盈无效 / Invalid stops', '止损 / 止盈价位无效（离现价太近或方向不对）', 'invalid stop loss / take profit (too close to the price or on the wrong side)'],
      ['与交易服务器断连 / No connection', '和券商服务器断开了', 'lost connection to the broker\'s server'],
      // 后端自己写的 / the backend's own wordings
      ['交易网关暂不支持该操作（网关版本待更新），本次指令未发出 / the trading gateway does not support this operation yet (pending a gateway update); nothing was sent', '网关暂不支持这个操作', 'the gateway does not support this operation yet'],
      ['交易网关暂时连不上，本次指令未发出，可稍后重试 / could not reach the trading gateway; nothing was sent, please try again shortly', '网关连不上，指令没发出', 'could not reach the gateway, nothing was sent'],
    ]
    for (const [msg, zhWhy, enWhy] of CODES) {
      expect(reasonOf(msg, zh), msg).toBe(zhWhy)
      expect(reasonOf(msg, en), msg).toBe(enWhy)
    }
  })

  it('认不出的原话：中文取中文那半，英文取英文那半，都没有按状态说 / unrecognised messages fall back sensibly', () => {
    // 中文原话：去掉「CODE: 」前缀和编号，半角标点换全角 / zh: code prefix and numbers dropped, punctuation widened
    expect(reasonOf('MT_RET_ERR_DATA: 服务器数据异常,请稍后再试 #12345678', zh)).toBe('服务器数据异常，请稍后再试')
    // 「中文 / English」各取各的 / each language takes its own half
    expect(reasonOf('网关内部出错 / Internal gateway error', zh)).toBe('网关内部出错')
    expect(reasonOf('网关内部出错 / Internal gateway error', en)).toBe('internal gateway error')
    // 太长截到 24 个字 / long Chinese is clipped to 24 characters
    const long = reasonOf('MT_RET_ERR_DATA: 这是一段非常非常长的券商说明文字，用来检查截断是否正常工作，后面还有更多内容', zh)!
    expect(long).toBe('这是一段非常非常长的券商说明文字，用来检查截断是…')
    expect(long.length).toBe(25)
    // 没有中文：被拒说「券商拒绝」，结果未知说「结果未知，请核对持仓」/ no Chinese: by status
    expect(reasonOf('MT_RET_ERR_DATA', zh, 'fail')).toBe('券商拒绝')
    expect(reasonOf('MT_RET_ERR_DATA', zh, 'unknown')).toBe('结果未知，请核对持仓')
    expect(reasonOf('MT_RET_ERR_DATA', en, 'fail')).toBe('rejected by the broker')
    expect(reasonOf('MT_RET_ERR_DATA', en, 'unknown')).toBe('outcome unknown, check positions')
    // 纯英文原话：中文句子说「券商拒绝」，英文句子去掉编号后照用 / plain English: zh generic, en cleaned
    expect(reasonOf('Some odd broker failure 10099', zh)).toBe('券商拒绝')
    expect(reasonOf('Some odd broker failure 10099', en)).toBe('some odd broker failure')
    // 只有英文的括号说明、英文词都不进中文句子 / English-only parentheticals and words never reach zh
    expect(reasonOf('MT_RET_ERR_DATA: 网关读取失败(read error) code ABC', zh)).toBe('网关读取失败')
  })

  it('每种指令都跟原因，一键平仓的明细也跟 / every instruction kind gets the reason, close-all children too', () => {
    const msg = 'MT_RET_REQUEST_NO_MONEY: 交易被拒绝(检查品种名、手数、保证金、市场是否开市)'
    const base = { sym: 'XAUUSD', side: 'BUY', msg, note: null }
    const cases: [string, Record<string, unknown>][] = [
      ['trade.open', { vol: 0.1 }],
      ['trade.close', { vol: 0.1, pos_vol: 0.1, partial: false, px: null, pnl: null, pnl_pending: false, gone: false }],
      ['auto.partial_tp', { vol: 0.05, pos_vol: 0.1, remain: 0.05, partial: true, px: null, pnl: null, gone: false }],
      ['sltp.modify', { pos_vol: 0.1, sl: 2395, prev_sl: 2390, sl_op: 'move', tp_op: 'same' }],
      ['auto.sl', { mode: 'be', sl: 2401.35, prev_sl: 2395, moves: 1 }],
      ['pending.place', { vol: 0.2, price: 2450, ptype: 'SELL_LIMIT' }],
      ['pending.modify', { price: 2455, sl_op: 'keep', tp_op: 'keep' }],
      ['pending.cancel', { vol: 0.2, price: 2450, ptype: 'SELL_LIMIT' }],
      ['trade.other', { action: 'HEDGE', vol: 0.1 }],
    ]
    for (const [kind, over] of cases) {
      for (const status of ['fail', 'unknown'] as const) {
        expect(renderEvent(item(kind, { ...base, ...over }, { status }), zh).text, kind).toMatch(/，原因：保证金不足$/)
        expect(renderEvent(item(kind, { ...base, ...over }, { status }), en).text, kind).toMatch(/, reason: not enough margin$/)
      }
      // 成功、处理中、已撤回的不说原因 / no reason for ok, pending or withdrawn
      for (const status of ['ok', 'pending', 'cancelled'] as const) {
        expect(renderEvent(item(kind, { ...base, ...over }, { status }), zh).text, kind).not.toContain('原因')
      }
    }
    const child = item('trade.close', { ...base, vol: 0.1, partial: false, px: null, pnl: null, gone: false, msg: 'MT_RET_REQUEST_CLOSE_ORDER_EXIST: x' }, { status: 'fail' })
    const all = item('trade.close_all', { count: 1, filled: 0, failed: 1 }, { status: 'fail', key: 'e:ca', children: [child] })
    expect(renderEvent(all, zh).text).not.toContain('原因')
    expect(renderEvent(all.children![0], zh).text).toBe('平仓 —— XAUUSD 买单 0.10 手，原因：这笔仓位已有平仓单在处理中')
  })

  it('不需要原因的：没有原话、超时、仓位已不在 / no reason without a message, for timeouts or gone positions', () => {
    expect(renderEvent(open(null), zh).text).toBe('开仓 —— XAUUSD 买单 5.00 手')
    expect(renderEvent(open('结果未知：这笔指令长时间没有收到执行结果', 'unknown', { note: 'timeout_unknown' }), zh).text).toBe(
      '开仓（超时，结果未知，请核对持仓） —— XAUUSD 买单 5.00 手',
    )
    const gone = item('trade.close', { sym: 'XAUUSD', side: 'BUY', vol: 0.1, gone: true, msg: 'Position already closed', note: 'gone' }, { status: 'fail', tags: ['gone'] })
    expect(renderEvent(gone, zh).text).not.toContain('原因')
  })

  it('中文原因里没有英文，英文原因里没有中文 / zh reasons hold no English, en reasons no Chinese', () => {
    const zhWhy = zh('admin.log.why', { returnObjects: true }) as Record<string, string>
    const enWhy = en('admin.log.why', { returnObjects: true }) as Record<string, string>
    expect(Object.keys(zhWhy).sort()).toEqual(Object.keys(enWhy).sort())
    for (const [k, v] of Object.entries(zhWhy)) expect(v, k).not.toMatch(/[A-Za-z]/)
    for (const [k, v] of Object.entries(enWhy)) {
      expect(v, k).not.toMatch(/[一-鿿]/)
      expect(v, k).not.toMatch(/\b[A-Z]{2,}\b/)
    }
  })
})

describe('平台设置与游戏化设置 / platform and gamification settings', () => {
  const admin = { type: 'admin' as const, id: 'a1', name: '运营小王', email: 'ops@x.com' }
  const setting = (params: Record<string, unknown>) => item('admin.setting', params, { cat: 'admin', user: null, login: null, account: null, actor: admin })
  // 2026-09-19 之前整组记一行 `setting:<group>`：后端报成 group=null、key=<group>、old=null、new=整组 JSON
  // Before 2026-09-19 a whole group was one `setting:<group>` row: group=null, key=<group>, old=null, new=the whole JSON
  const legacy = (group: string, value: unknown) =>
    setting({ group: null, key: group, old: null, new: value, changes: [{ group: null, key: group, old: null, new: value }] })
  const pricing = { pro_monthly_price: 39, pro_yearly_price: 299, sale_enabled: false, sale_percent: 0, sale_badge: '', sale_end_at: null }

  it('旧式整组行按组名说、逐项列出，不再读成「合作券商限制：pricing已修改」/ legacy whole-group rows name their group', () => {
    const zhText = renderEvent(legacy('pricing', pricing), zh).text
    expect(zhText).toBe('修改平台设置 · 订阅定价：月付价格 → 39；年付价格 → 299；另有 4 项')
    expect(renderEvent(legacy('pricing', pricing), en).text).toBe(
      'Changed platform settings · Pricing: monthly price → 39; yearly price → 299; and 4 more',
    )
    expect(renderEvent(legacy('trial', { trial_enabled: true, trial_days: 7 }), zh).text).toBe('修改平台设置 · 免费试用：免费试用 → 开；试用天数 → 7')
    expect(renderEvent(legacy('winrate', { public_strategies: ['金牛', '银狐'] }), zh).text).toBe('修改平台设置 · 策略胜率公开：公开的策略 → 金牛、银狐')
    // 策略介绍记的是 {count, ids}：一句「调整了列表」/ platform_strategies logs {count, ids}: one fixed sentence
    expect(renderEvent(legacy('platform_strategies', { count: 2, ids: ['400fbc33-279f-4637-839f-67e631a9a4a3'] }), zh).text).toBe(
      '调整了策略介绍页的策略列表',
    )
    for (const g of ['pricing', 'trial', 'email_gate', 'social', 'candle_history', 'strategy', 'strategy_costs', 'winrate']) {
      for (const [lang, t] of LANGS) {
        const text = renderEvent(legacy(g, { m1_retention_days: 30 }), t).text
        expect(text, g).not.toContain('合作券商限制')
        expect(text, g).not.toMatch(/Partner broker/)
        expect(text, g).not.toMatch(/\b[a-z]+_[a-z_]+\b/)
        // 中文句子里不该出现英文的组名 / no English group name inside a zh sentence
        if (lang === 'zh') expect(text, g).not.toMatch(/[a-z]{2,}/)
      }
    }
  })

  it('后端规整成 group=<组>、key=null 的写法同样认 / the normalised group=<group>, key=null form reads the same', () => {
    const norm = setting({ group: 'pricing', key: null, old: null, new: pricing, changes: [{ group: 'pricing', key: null, old: null, new: pricing }] })
    expect(renderEvent(norm, zh).text).toBe('修改平台设置 · 订阅定价：月付价格 → 39；年付价格 → 299；另有 4 项')
    // 已经逐键拆好、旧值为空：只说改成了什么 / already split per key, old null: just what it became
    const split = setting({ group: 'pricing', key: 'pro_monthly_price', old: null, new: 39, changes: [{ group: 'pricing', key: 'pro_monthly_price', old: null, new: 39 }] })
    expect(renderEvent(split, zh).text).toBe('修改平台设置 · 订阅定价：月付价格 → 39')
  })

  it('券商锁那组的两段式键照旧 / the broker lock’s two-part keys are unchanged', () => {
    const broker = setting({ group: null, key: 'broker_lock_enabled', old: false, new: true, changes: [{ group: null, key: 'broker_lock_enabled', old: false, new: true }] })
    expect(renderEvent(broker, zh).text).toBe('修改平台设置 · 合作券商限制：启用券商限制 关 → 开')
  })

  const UUID_A = '400fbc33-279f-4637-839f-67e631a9a4a3'
  const UUID_B = 'aaaabbbb-cccc-4ddd-8eee-ffff00001111'
  const gam = (c: Record<string, unknown>) =>
    item('admin.gamification', { key: 'featured_competition_id', old: c.old, new: c.new, changes: [{ key: 'featured_competition_id', ...c }] }, { cat: 'admin', user: null, login: null, account: null, actor: admin })

  it('推荐比赛：设了 / 换了 / 取消，句子里绝不出比赛 id / featured competition: set, switched, cleared — never an id', () => {
    expect(renderEvent(gam({ old: null, new: UUID_A }), zh).text).toBe('修改游戏化设置：设置了推荐比赛')
    expect(renderEvent(gam({ old: UUID_A, new: UUID_B }), zh).text).toBe('修改游戏化设置：更换了推荐比赛')
    expect(renderEvent(gam({ old: UUID_A, new: null }), zh).text).toBe('修改游戏化设置：取消了推荐比赛（改回自动挑选）')
    expect(renderEvent(gam({ old: UUID_A, new: null }), en).text).toBe('Changed gamification settings: featured competition cleared (back to automatic)')
    // 后端带上比赛名时用名字 / with names from the backend, the names are used
    expect(renderEvent(gam({ old: UUID_A, new: UUID_B, old_name: '十月实盘赛', new_name: '十一月实盘赛' }), zh).text).toBe(
      '修改游戏化设置：推荐比赛 「十月实盘赛」 → 「十一月实盘赛」',
    )
    expect(renderEvent(gam({ old: null, new: UUID_B, new_name: '十一月实盘赛' }), zh).text).toBe('修改游戏化设置：推荐比赛 → 「十一月实盘赛」')
    for (const c of [{ old: null, new: UUID_A }, { old: UUID_A, new: UUID_B }, { old: UUID_A, new: null }]) {
      for (const [, t] of LANGS) expect(renderEvent(gam(c), t).text).not.toMatch(/[0-9a-f]{8}-[0-9a-f]{4}/)
    }
  })

  it('兜底的值里出现 uuid 也不进句子 / a uuid value never reaches a sentence, even in the fallback', () => {
    const other = item('admin.other', { field: 'something:new', old: null, new: UUID_A }, { cat: 'admin' })
    const text = renderEvent(other, zh).text
    expect(text).not.toContain(UUID_A)
    expect(text).toContain('something:new')
  })
})

describe('数字格式 / number formats', () => {
  it('盈亏带正负号与千分位，四舍五入后的 0 不带号 / signed P/L with grouping; a rounded zero is unsigned', () => {
    expect(fmtPnl(1234.5)).toBe('+1,234.50')
    expect(fmtPnl(-48.5)).toBe('-48.50')
    expect(fmtPnl(-0.001)).toBe('0.00')
    expect(fmtPnl(0)).toBe('0.00')
  })
  it('手数至少两位小数，价格按值本身的位数对齐 / lots ≥2dp; prices align on their own decimals', () => {
    expect(fmtLots(0.1)).toBe('0.10')
    expect(fmtLots(1)).toBe('1.00')
    expect(fmtLots(0.125)).toBe('0.125')
    expect(pxDigits(2640, 2648.5)).toBe(2)
    expect(pxDigits(1.0821, 1.09)).toBe(4)
    expect(pxDigits(null, 149.325)).toBe(3)
  })

  it('品种认得：不少于它的报价精度；认不出：一句里对齐 / known symbols keep their quote precision, others align within the sentence', () => {
    expect(symDigits('EURUSD', 1.085)).toBe(5)
    expect(symDigits('EURUSD.s', 1.085)).toBe(5)
    expect(symDigits('USDJPY', 149.32)).toBe(3)
    expect(symDigits('XAUUSD', 2400)).toBe(2)
    // 券商给的位数比兜底表多：跟价格本身 / a broker quoting more digits than the table wins
    expect(symDigits('XAUUSD', 2401.355)).toBe(3)
    expect(symDigits('FOOBAR', 1.5)).toBe(2)
    expect(symDigits(null, 1.0821, 1.09)).toBe(4)
  })

  it('同一句里的价格位数一致 / prices in one sentence share their decimals', () => {
    const sltp = (over: Record<string, unknown>) =>
      item('sltp.modify', { sym: 'EURUSD', side: 'SELL', pos_vol: null, sl: null, tp: null, prev_sl: null, prev_tp: null, sl_op: 'same', tp_op: 'same', ...over })
    // 设计验收时的那句：EURUSD 是 5 位，「原 1.085」要读成「原 1.08500」
    // The sentence from the design review: EURUSD has 5 digits, so "was 1.085" reads "was 1.08500"
    expect(renderEvent(sltp({ prev_tp: 1.085, tp_op: 'remove' }), zh).text).toBe('移除止盈（原 1.08500），止损不变 —— EURUSD 卖单')
    expect(renderEvent(sltp({ prev_tp: 1.085, tp_op: 'remove' }), en).text).toBe('Remove take profit (was 1.08500), stop loss unchanged — EURUSD sell')
    expect(renderEvent(sltp({ sl: 1.0921, prev_sl: 1.09, sl_op: 'move' }), zh).text).toBe('移动止损 1.09000 → 1.09210，止盈不变 —— EURUSD 卖单')
    // 认不出的品种：按这一句里位数最多的价格对齐 / unknown symbol: aligned on the longest price in the sentence
    expect(renderEvent(sltp({ sym: 'FOOBAR', sl: 1.2345, sl_op: 'set', prev_tp: 1.5, tp_op: 'remove' }), zh).text).toBe(
      '设置止损 1.2345，移除止盈（原 1.5000） —— FOOBAR 卖单',
    )
    // 成交价、触发价同样 / fill and trigger prices too
    const open = item('trade.open', { sym: 'USDJPY', side: 'BUY', vol: 0.2, px: 149.32, sl: 148.5, tp: null, src: 'CHART', note: null })
    expect(renderEvent(open, zh).text).toBe('开仓 —— USDJPY 买单 0.20 手，成交价 149.320，止损 148.500')
    const pend = item('pending.cancel', { sym: 'EURUSD', side: 'SELL', vol: 0.2, price: 1.1, ptype: 'SELL_LIMIT' })
    expect(renderEvent(pend, zh).text).toBe('撤销限价卖单 —— EURUSD 0.20 手，触发价 1.10000')
    const deal = item('deal.close', { reason: 'TP', sym: 'GBPUSD', side: 'BUY', vol: 0.1, px: 1.27, pnl: 10, leg_k: 1, leg_n: 1, holders: null })
    expect(renderEvent(deal, zh).text).toContain('成交价 1.27000')
  })
})

describe('容错 / robustness', () => {
  it('params 缺键也拼得出句子，不出 undefined / missing params still render, no undefined', () => {
    for (const [, t] of LANGS) {
      for (const k of ACTIVITY_KINDS) {
        const text = renderEvent(item(k, {}), t).text
        expect(text.length, k).toBeGreaterThan(1)
        expect(text, k).not.toMatch(/undefined|NaN|admin\.log\.|\{\{/)
      }
    }
  })

  it('渲染时抛错退回这个 kind 的通用说法 / a renderer that throws falls back to the kind’s name', () => {
    const hostile = new Proxy({}, { get: () => { throw new Error('boom') } }) as Record<string, unknown>
    expect(renderEvent(item('trade.open', hostile), zh).text).toBe('开仓指令')
    expect(renderEvent(item('trade.open', hostile), en).text).toBe('Open instruction')
  })

  it('认不出的 kind 照样显示一行 / an unknown kind still gets a line', () => {
    expect(renderEvent(item('future.kind', { a: 1 }), zh).text).toContain('认不出')
    expect(renderEvent(item('future.kind', { a: 1 }), en).text).toContain('Unrecognised')
  })
})

describe('谁操作与小标签 / actor and chips', () => {
  it('谁操作 / actor labels', () => {
    const a = (type: ActivityItem['actor']['type'], name: string | null = null, email: string | null = null) =>
      actorLabel(item('admin.other', {}, { actor: { type, id: name ? 'x' : null, name, email } }), zh)
    expect(a('self')).toBe('本人')
    expect(a('auto')).toBe('自动仓管')
    expect(a('broker')).toBe('券商（MT5）')
    expect(a('admin', '运营小王', 'ops@x.com')).toBe('管理员 运营小王')
    expect(a('admin', null, 'ops@x.com')).toBe('管理员 ops@x.com')
    expect(a('agent', null, null)).toBe('代理')
  })
  it('部分平仓 / 仓位已不在 / 自动 不再做成小标签（句子和「谁操作」已经说了）/ partial, gone, auto get no chip', () => {
    const it2 = item('auto.partial_tp', {}, { tags: ['auto', 'partial', 'late', 'shared_login'], status: 'pending' })
    expect(chipsFor(it2, en).map((c) => c.label)).toEqual(['Pending', 'Recorded late', 'Shared account'])
  })
})
